### ISSUE TITLE
Legacy extension stops working since VSCode 1.73

### ISSUE THREAD

**Issue by mkloubert** [vscode-kanban/vscode-kanban#17]
Hi @mkloubert, I know its wrong place to put this, but I couldn't create new issues on your old [mkloubert/vscode-kanban](https://github.com/mkloubert/vscode-kanban) as its in read-only mode now. I updated vscode to 1.73.0 and the extension stop working, so i had to downgrade vscode to 1.72.2 and it worked again. Would you mind spending time to check the issues, thanks in advance. My system: ubuntu:22.04.1, vscode: 1.73.0, kanban:v1.33.1

_Originally posted by @nqoptic in https://github.com/vscode-kanban/vscode-kanban/issues/16#issuecomment-1308968979_

**Comment by mkloubert** [comment]
@nqoptic

update `1.33.2` should be fix the issue

**Comment by nqoptic** [comment]
@mkloubert Its working now, appreciates your time
